name: Build OnePlus SM8750 Kernel

on:
  workflow_dispatch:        # Allows manual triggering from GitHub UI
  push:
    branches: [ main ]      # Auto-run when pushing to main branch
  pull_request:
    branches: [ main ]      # Run on PRs targeting main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Latest Ubuntu runner
    
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Get full git history for version tagging

      # Set up build environment
      - name: Set up build tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            git-core gnupg flex bison build-essential zip curl \
            zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev \
            libgl1-mesa-dev libxml2-utils xsltproc unzip python3 bc

      # Make script executable and build
      - name: Build kernel
        run: |
          chmod +x Build_Kernel.sh
          ./Build_Kernel.sh

      # Upload artifacts (AK3 zip files)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-build-${{ github.run_id }}
          path: |
            *.zip
            Image*
          if-no-files-found: error
          retention-days: 7

      # Optional: Post-build cleanup
      - name: Clean up
        if: always()
        run: |
          make clean || true
          rm -rf out/ || true
